### ISSUE TITLE
Exception when file cannot be found

### ISSUE THREAD

**Issue by skion** [mikelolasagasti/revelation#4]
``` python
Traceback (most recent call last):
  File "/usr/bin/revelation", line 1833, in <module>
    app.run()
  File "/usr/bin/revelation", line 1591, in run
    self.file_open(io.file_normpath(file))
  File "/usr/bin/revelation", line 1481, in file_open
    entrystore = self.__file_load(file, password)
  File "/usr/bin/revelation", line 1019, in __file_load
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by lkmcs** [comment]
I think this can be closed, looks like it's duplicate and problem will be solved in 0.5.2 https://github.com/mikelolasagasti/revelation/issues/24
