### ISSUE TITLE
Error to export to Figaro

### ISSUE THREAD

**Issue by gpoo** [mikelolasagasti/revelation#63]
When I tried to export a file to Figaro, I get the following trace:

```
Traceback (most recent call last):
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 239, in <lambda>
    action.connect("activate",      lambda w,k: self.file_export())
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 1495, in file_export
    datafile.save(self.entrystore, file, password)
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/io.py", line 123, in save
    file_write(file, self.__handler.export_data(entrystore, password))
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/datahandler/fpm.py", line 153, in export_data
    password = MD5.new(salt + password).digest()
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/MD5.py", line 158, in new
    return MD5Hash().new(data)
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/MD5.py", line 145, in new
    return MD5Hash(data)
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/MD5.py", line 81, in __init__
    self.update(data)
  File "/usr/lib/python3/dist-packages/Cryptodome/Hash/MD5.py", line 91, in update
    c_uint8_ptr(data),
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 196, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

**Comment by gpoo** [comment]
Same error when trying to export to GPass 0.4.
