### ISSUE TITLE
[Regression] Error to export to My Password Safe

### ISSUE THREAD

**Issue by gpoo** [mikelolasagasti/revelation#64]
Similar to issue #62 but the trace is:

```
Traceback (most recent call last):
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 239, in <lambda>
    action.connect("activate",      lambda w,k: self.file_export())
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 1495, in file_export
    datafile.save(self.entrystore, file, password)
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/io.py", line 123, in save
    file_write(file, self.__handler.export_data(entrystore, password))
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/datahandler/pwsafe.py", line 574, in export_data
    edata += create_field(uuid, FIELDTYPE_UUID)
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/datahandler/pwsafe.py", line 333, in create_field
    field = struct.pack("ii", len(value), type) + value
TypeError: can't concat str to bytes
```

**Comment by gpoo** [comment]
Similar, although no exactly the same when export to My Password Manager old format:

```
Traceback (most recent call last):
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 239, in <lambda>
    action.connect("activate",      lambda w,k: self.file_export())
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/bin/revelation", line 1495, in file_export
    datafile.save(self.entrystore, file, password)
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/io.py", line 123, in save
    file_write(file, self.__handler.export_data(entrystore, password))
  File "/home/gpoo/.var/app/org.gnome.Builder/cache/gnome-builder/install/revelation-next/host/lib/python3.8/site-packages/revelation/datahandler/pwsafe.py", line 411, in export_data
    edata += create_field(e.name.encode(enc, "replace") + "\xAD" + e[entry.UsernameField].encode("iso-8859-1"))
TypeError: can't concat str to bytes
```

**Comment by gpoo** [comment]
Same error with the same traceback when exporting to Gorilla,

**Comment by gpoo** [comment]
Ditto for Password Safe v2.x
